"use strict";

/** Provider types Crush names in schema + command reference. */
const PROVIDER_TYPES = [
  "openai",
  "openai-compat",
  "anthropic",
  "ollama",
  "openrouter",
  "azure",
  "bedrock",
  "google",
  "google-vertex",
  "hyper",
  "litellm",
  "llamacpp",
  "lmstudio",
  "omlx",
  "vercel",
];

const MCP_TYPES = ["stdio", "sse", "http"];

const MODEL_SLOTS = ["large", "small"];

const HOOK_EVENTS = ["PreToolUse"];

const NOTIFICATION_STYLES = ["auto", "native", "osc", "bell", "disabled"];

const TRAILER_STYLES = ["none", "co-authored-by", "assisted-by"];

const DIFF_MODES = ["unified", "split"];

const SCROLLBAR_MODES = ["default", "always", "never"];

const REASONING_EFFORTS = ["low", "medium", "high"];

/** Highest Crush-documented reasoning effort (`model … --reasoning-effort`). */
const MAX_REASONING_EFFORT = "high";

/** Crush `defaultModel()` fallback when a catalog model omits context_window. */
const DEFAULT_CONTEXT_WINDOW = 128000;

const PROJECT_CONFIG_NAMES = [".crushrc", "crushrc", ".crush.json", "crush.json"];

/** Merge order within one directory: later wins. */
const PROJECT_MERGE_ORDER = ["crush.json", ".crush.json", "crushrc", ".crushrc"];

const PROJECT_SKILL_SUBDIRS = [
  ".agents/skills",
  ".crush/skills",
  ".claude/skills",
  ".cursor/skills",
];

const SECTIONS = [
  "models",
  "skills",
  "mcp",
  "lsp",
  "hooks",
  "permissions",
  "options",
  "env",
];

/** User-facing option keys that map onto JSON options. */
const OPTION_SPECS = {
  debug: { jsonKey: "debug", kind: "bool" },
  "debug-lsp": { jsonKey: "debug_lsp", kind: "bool" },
  "auto-lsp": { jsonKey: "auto_lsp", kind: "bool" },
  progress: { jsonKey: "progress", kind: "bool" },
  metrics: { jsonKey: "disable_metrics", kind: "bool", inverted: true },
  "auto-summarize": { jsonKey: "disable_auto_summarize", kind: "bool", inverted: true },
  "provider-auto-update": { jsonKey: "disable_provider_auto_update", kind: "bool", inverted: true },
  "default-providers": { jsonKey: "disable_default_providers", kind: "bool", inverted: true },
  notifications: { jsonKey: "notifications", kind: "string" },
  "data-directory": { jsonKey: "data_directory", kind: "string" },
  "initialize-as": { jsonKey: "initialize_as", kind: "string" },
  "context-path": { jsonKey: "context_paths", kind: "list" },
  "global-context-path": { jsonKey: "global_context_paths", kind: "list" },
  "skill-path": { jsonKey: "skills_paths", kind: "list" },
  "disable-skill": { jsonKey: "disabled_skills", kind: "list" },
};

const MANAGED_CRUSHRC_MARK = "# Generated by crush-setup. Builtin commands only.";

const JSON_SCHEMA_URL = "https://charm.land/crush.json";

module.exports = {
  PROVIDER_TYPES,
  MCP_TYPES,
  MODEL_SLOTS,
  HOOK_EVENTS,
  NOTIFICATION_STYLES,
  TRAILER_STYLES,
  DIFF_MODES,
  SCROLLBAR_MODES,
  REASONING_EFFORTS,
  MAX_REASONING_EFFORT,
  DEFAULT_CONTEXT_WINDOW,
  PROJECT_CONFIG_NAMES,
  PROJECT_MERGE_ORDER,
  PROJECT_SKILL_SUBDIRS,
  SECTIONS,
  OPTION_SPECS,
  MANAGED_CRUSHRC_MARK,
  JSON_SCHEMA_URL,
};
